/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantToolsFileSearch {
    /// The type of tool being defined: `file_search`
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AssistantToolsFileSearch {
    pub fn new(r#type: Type) -> AssistantToolsFileSearch {
        AssistantToolsFileSearch {
            r#type,
        }
    }
}
/// The type of tool being defined: `file_search`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file_search")]
    FileSearch,
}

impl Default for Type {
    fn default() -> Type {
        Self::FileSearch
    }
}

