/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVectorStoreFileRequest {
    /// A [File](/docs/api-reference/files) ID that the vector store should use. Useful for tools like `file_search` that can access files.
    #[serde(rename = "file_id")]
    pub file_id: String,
}

impl CreateVectorStoreFileRequest {
    pub fn new(file_id: String) -> CreateVectorStoreFileRequest {
        CreateVectorStoreFileRequest {
            file_id,
        }
    }
}

