/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageObjectAttachmentsInner {
    /// The ID of the file to attach to the message.
    #[serde(rename = "file_id", skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
    /// The tools to add this file to.
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<models::MessageObjectAttachmentsInnerToolsInner>>,
}

impl MessageObjectAttachmentsInner {
    pub fn new() -> MessageObjectAttachmentsInner {
        MessageObjectAttachmentsInner {
            file_id: None,
            tools: None,
        }
    }
}

