/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageObjectAttachmentsInnerToolsInner {
    AssistantToolsCode(Box<models::AssistantToolsCode>),
    AssistantToolsFileSearch(Box<models::AssistantToolsFileSearch>),
}

impl Default for MessageObjectAttachmentsInnerToolsInner {
    fn default() -> Self {
        Self::AssistantToolsCode(Default::default())
    }
}
/// The type of tool being defined: `code_interpreter`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "code_interpreter")]
    CodeInterpreter,
    #[serde(rename = "file_search")]
    FileSearch,
}

impl Default for Type {
    fn default() -> Type {
        Self::CodeInterpreter
    }
}

